name: Test and Build PR

on:
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '12.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Node.js modules
      uses: actions/cache@v1
      with:
        path: ./node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
        
    - name: Install dependencies
      run: npm install

    - name: Check lint errors
      run: npm run lint

    - name: Test app
      run: npm run test

    - name: Build app
      run: npm run build
